/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;


/**
 *
 * @author Usuario
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public VentanaMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
       this.setTitle("CANCIONERO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonGeneros = new javax.swing.JButton();
        BotonAnalisis = new javax.swing.JButton();
        BotonAcordes = new javax.swing.JButton();
        BotonPlaylist = new javax.swing.JButton();
        BotonArtistas = new javax.swing.JButton();
        BotonCanciones = new javax.swing.JButton();
        BotonCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonGeneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Generosb1.png"))); // NOI18N
        BotonGeneros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonGeneros.setBorderPainted(false);
        BotonGeneros.setContentAreaFilled(false);
        BotonGeneros.setFocusPainted(false);
        BotonGeneros.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Generosb2.png"))); // NOI18N
        BotonGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 340, 60));

        BotonAnalisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Analisisb1.png"))); // NOI18N
        BotonAnalisis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonAnalisis.setBorderPainted(false);
        BotonAnalisis.setContentAreaFilled(false);
        BotonAnalisis.setFocusPainted(false);
        BotonAnalisis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Analisisb2.png"))); // NOI18N
        BotonAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalisisActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 340, 60));

        BotonAcordes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Acordesb1.png"))); // NOI18N
        BotonAcordes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonAcordes.setBorderPainted(false);
        BotonAcordes.setContentAreaFilled(false);
        BotonAcordes.setFocusPainted(false);
        BotonAcordes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Acordesb2.png"))); // NOI18N
        BotonAcordes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcordesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAcordes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 340, 60));

        BotonPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Playlistb1.png"))); // NOI18N
        BotonPlaylist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonPlaylist.setBorderPainted(false);
        BotonPlaylist.setContentAreaFilled(false);
        BotonPlaylist.setFocusPainted(false);
        BotonPlaylist.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Playlistb2.png"))); // NOI18N
        BotonPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPlaylistActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 340, 60));

        BotonArtistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Artitasb1.png"))); // NOI18N
        BotonArtistas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonArtistas.setBorderPainted(false);
        BotonArtistas.setContentAreaFilled(false);
        BotonArtistas.setFocusPainted(false);
        BotonArtistas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Artitasb2.png"))); // NOI18N
        BotonArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArtistasActionPerformed(evt);
            }
        });
        getContentPane().add(BotonArtistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 340, 60));

        BotonCanciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Cancionesb1.png"))); // NOI18N
        BotonCanciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonCanciones.setBorderPainted(false);
        BotonCanciones.setContentAreaFilled(false);
        BotonCanciones.setFocusPainted(false);
        BotonCanciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Cancionesb2.png"))); // NOI18N
        BotonCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancionesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCanciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 60));

        BotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Cerrarb1 (2).png"))); // NOI18N
        BotonCerrar.setBorder(null);
        BotonCerrar.setBorderPainted(false);
        BotonCerrar.setContentAreaFilled(false);
        BotonCerrar.setFocusPainted(false);
        BotonCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Cerrarb2 (2).png"))); // NOI18N
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 70, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/patnprin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCancionesActionPerformed

    private void BotonArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArtistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonArtistasActionPerformed

    private void BotonGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGenerosActionPerformed

    private void BotonAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalisisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAnalisisActionPerformed

    private void BotonPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPlaylistActionPerformed

    private void BotonAcordesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcordesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAcordesActionPerformed

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCerrarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAcordes;
    public javax.swing.JButton BotonAnalisis;
    public javax.swing.JButton BotonArtistas;
    public javax.swing.JButton BotonCanciones;
    public javax.swing.JButton BotonCerrar;
    public javax.swing.JButton BotonGeneros;
    public javax.swing.JButton BotonPlaylist;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
